version: '3.8'

services:
  telegram-bot:
    build: .
    shm_size: '2g'
    container_name: telegram-phishing-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - VIRUSTOTAL_API_KEY=${VIRUSTOTAL_API_KEY}
      - WEBRISK_API_KEY=${WEBRISK_API_KEY}
      - ADMIN_USER_ID=${ADMIN_USER_ID}  # Optional, for admin commands
      - GEMINI_APIKEY=${GEMINI_API_KEY}  # Optional, for AI analysis
